development: &defaults
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

  # adapter: mysql2
  # encoding: utf8
  # database: my_db_name
  # username: root
  # password: my_password
  # host: 127.0.0.1
  # port: 3306

  # adapter: postgresql
  # database: blog_development
  # username: foo
  # password: bar
  # encoding: unicode
  # pool: 5

test:
  <<: *defaults
  database: db/test.sqlite3

production:
  <<: *defaults
  database: db/production.sqlite3