development: &defaults
  # adapter: sqlite3
  # database: db/development.sqlite3
  # pool: 5
  # timeout: 5000

  # adapter: mysql2
  # host: 127.0.0.1
  # port: 3306
  # username: migrations
  # password: foobar
  # database: migrations_development
  # encoding: utf8

  adapter: postgresql
  host: 127.0.0.1
  port: 5432
  username: migrations
  password: foobar
  database: migrations_development
  encoding: unicode
  pool: 5

test:
  <<: *defaults
  # database: db/test.sqlite3

  database: migrations_test

production:
  <<: *defaults
  # database: db/production.sqlite3

  database: migrations_production